name: Build ZMK firmware locally for split keyboard

on:
  workflow_dispatch:  # can be triggered manually

jobs:
  build-local:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        echo "base_dir=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
        echo "build_dir=$(mktemp -d)" >> $GITHUB_ENV
        echo "config_path=config" >> $GITHUB_ENV

    - name: West Init
      working-directory: ${{ env.base_dir }}
      run: |
        if [ ! -d ".west" ]; then
          west init -l "${{ env.base_dir }}/${{ env.config_path }}"
        fi

    - name: West Update
      working-directory: ${{ env.base_dir }}
      run: west update

    - name: West Zephyr export
      working-directory: ${{ env.base_dir }}
      run: west zephyr-export

    - name: Set timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

    - name: West Build (Left Half)
      working-directory: ${{ env.base_dir }}
      run: |
        west build -s zmk/app -d "${{ env.build_dir }}_left" -b nice_nano_v2 -- -DZMK_CONFIG=${{ env.base_dir }}/${{ env.config_path }} -DSHIELD=splitkb_aurora_sweep_left
        mkdir -p ${{ github.workspace }}/builds
        cp ${{ env.build_dir }}_left/zephyr/zmk.uf2 ${{ github.workspace }}/builds/left_half_${TIMESTAMP}.uf2

    - name: West Build (Right Half)
      working-directory: ${{ env.base_dir }}
      run: |
        west build -s zmk/app -d "${{ env.build_dir }}_right" -b nice_nano_v2 -- -DZMK_CONFIG=${{ env.base_dir }}/${{ env.config_path }} -DSHIELD=splitkb_aurora_sweep_right
        cp ${{ env.build_dir }}_right/zephyr/zmk.uf2 ${{ github.workspace }}/builds/right_half_${TIMESTAMP}.uf2

    - name: List contents of builds directory
      run: ls -l ${{ github.workspace }}/builds

    - name: Debug Information
      run: |
        echo "ZEPHYR_BASE: $ZEPHYR_BASE"
        echo "ZEPHYR_SDK_INSTALL_DIR: $ZEPHYR_SDK_INSTALL_DIR"
        west --version
        cmake --version
        env | sort
