# Draw keymap diagrams using keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - 'config/*.keymap'
      - keymap-drawer/config.yaml
      - .github/workflows/draw-keymaps.yml
jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: 'config/*.keymap'
      config_path: keymap-drawer/config.yaml
      output_folder: keymap-drawer
      amend_commit: true
